model:
  name: CoEvolNO
  coord_dim: 7
  in_channels: 0
  depth: 8
  dim_lat: 128
  dim_tok: 128
  num_latents: 128
  num_heads: 8
  mlp_ratio: 1.0
  drop_path_rate: 0.1
  use_pc_ffn: false
  pc_ffn_loss_type: 'dot product'
  pc_ffn_momentum_beta: 0.9
  pc_ffn_analytical: true

training:
  lr: 0.001
  epochs: 200
  batch_size: 1
